### ISSUE TITLE
How to use with JSON data from remote server?

### ISSUE THREAD

**Issue by n0490b** [rajan-g/ng2-typeahead#1]
Is it possible to feed this autocomplete json data from a remote server?

**Comment by rajan-g** [comment]
Hi, 
  This module support remote data feeding. refer example code, It have a property **"asynchDataCall".**
it has two params, **value**  will receive user input cb is a other one. after your remote service invocation (data fetching from server) do your data customization and pass to **cb**  method invocation 
example : **cb(result);**
